version: "3.2"
services:
  apache:
    build:
        context: ./
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./loris/:/var/www/
  mysql:
    image: mysql:5.7.28
    restart: always
    ports:
        - "8082:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=neopass
networks:
  frontend:
  backend:
