version: "3.2"
services:
  apache-php:
    build:
        context: ./loris_docker
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./loris/:/var/www/
    links:
      - mysql

  mysql:
    build:
        context: ./mysql_docker
    restart: always
    ports:
        - "8082:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=neopass
